# Generated by Django 3.1.4 on 2021-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofileinfo',
            name='typeoffaculty',
            field=models.CharField(choices=[('ap', 'ap'), ('app', 'app'), ('af', 'af'), ('hod', 'hod')], max_length=200, null=True),
        ),
    ]
