# Generated by Django 3.1.4 on 2021-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0002_facultyprofileinfo_typeoffaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofileinfo',
            name='typeoffaculty',
            field=models.CharField(choices=[('Assistant Professor', 'ap'), ('Associate Professor', 'aap'), ('Adjunct Faculty', 'af'), ('Head of department', 'hod')], max_length=200, null=True),
        ),
    ]
