# Generated by Django 3.1.4 on 2021-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0003_auto_20210109_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofileinfo',
            name='typeoffaculty',
            field=models.CharField(choices=[('ap', 'Assistant Professor'), ('aap', 'Associate Professor'), ('af', 'Adjunct Faculty'), ('hod', 'Head of department')], max_length=200, null=True),
        ),
    ]
