# Generated by Django 3.1.4 on 2021-01-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0005_researchinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placementstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=200)),
            ],
        ),
    ]
