# Generated by Django 3.1.4 on 2021-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0006_placementstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementstat',
            name='programme',
        ),
        migrations.AddField(
            model_name='placementstat',
            name='btech',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='placementstat',
            name='mca',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='placementstat',
            name='mtech',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='placementstat',
            name='year',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='placementstat',
            name='percentage',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
