# Generated by Django 3.1.4 on 2021-01-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkapp', '0008_coursesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesinfo',
            name='name',
            field=models.CharField(default='sub', max_length=200),
        ),
    ]
